services:
  - type: web
    name: line-bot-java
    env: docker
    dockerContext: ./
    plan: free
    autoDeploy: false
    envVars:
      - key: CHANNEL_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false